export const TEMPLATES = [
  {
    id: 'moonlit',
    title: 'The Moonlit Adventure',
    theme: 'bedtime & dreams',
    idea: 'A child who befriends a sleepy moon and sails across a starry sky to help the moon find its way home before morning.',
    image: '/images/templates/moonlit.jpg',
    accent: 'from-indigo-200 to-blue-100',
  },
  {
    id: 'seed',
    title: 'The Tiny Seed',
    theme: 'nature & growth',
    idea: 'A tiny seed learns about patience, rain, and sunshine as it grows into a flower that lights up a whole garden.',
    image: '/images/templates/seed.jpg',
    accent: 'from-emerald-200 to-lime-100',
  },
  {
    id: 'forest',
    title: 'Forest Friends',
    theme: 'friendship & kindness',
    idea: 'A shy fox, a bouncy rabbit, and a wise deer team up to throw a surprise forest party for a lonely hedgehog.',
    image: '/images/templates/forest.jpg',
    accent: 'from-amber-200 to-orange-100',
  },
  {
    id: 'explorer',
    title: 'The Little Explorer',
    theme: 'courage & discovery',
    idea: 'A young explorer follows a map of doodles over hills and rivers to discover that the treasure was the journey itself.',
    image: '/images/templates/explorer.jpg',
    accent: 'from-orange-200 to-rose-100',
  },
  {
    id: 'sea',
    title: 'Under the Sea',
    theme: 'wonder & curiosity',
    idea: 'A gentle whale gives a curious child a ride through a glowing coral city where fish make music out of bubbles.',
    image: '/images/templates/sea.jpg',
    accent: 'from-cyan-200 to-teal-100',
  },
  {
    id: 'stars',
    title: 'The Star Keeper',
    theme: 'magic & wonder',
    idea: 'A child who collects fallen stars discovers one tiny star is homesick and sets off on a cozy quest to return it to the sky.',
    image: '/images/templates/stars.jpg',
    accent: 'from-violet-200 to-indigo-100',
  },
  {
    id: 'timid-dragon',
    title: 'The Timid Dragon',
    theme: 'bravery & bedtime',
    idea: 'A friendly dragon who is afraid of the dark learns that the night sky is full of gentle light and new friends.',
    image: '/images/templates/timid-dragon.jpg',
    accent: 'from-indigo-200 to-violet-100',
  },
  {
    id: 'rainbow-cloud',
    title: 'The Rainbow Cloud',
    theme: 'wonder & dreams',
    idea: 'A cheerful little cloud who wants to become a rainbow discovers that kindness is what gives it color.',
    image: '/images/templates/rainbow-cloud.jpg',
    accent: 'from-sky-200 to-rose-100',
  },
  {
    id: 'baking-bear',
    title: 'The Baking Bear',
    theme: 'cozy & friendship',
    idea: 'A cuddly bear learns to bake a birthday cake for a friend, with a few floury mishaps along the way.',
    image: '/images/templates/baking-bear.jpg',
    accent: 'from-amber-200 to-orange-100',
  },
];

export const STORY_IDEAS = [
  'A lost sock goes on a journey to find its pair',
  'A garden snail dreams of racing in the big meadow',
  'A moonbeam that gets stuck in a jar of honey',
  'A puddle that leads to a tiny underwater world',
  'A wind that has lost its whistle',
];
